/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bitmap.transformer;

import org.junit.Test;
import static org.junit.Assert.*;

public class BitmapTest {
    @Test public void testAppHasAGreeting() {
        Bitmap classUnderTest = new Bitmap();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
